  name: CI

  on:
    push:
    pull_request:

  jobs:
    run-tests:
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          python-versions:
            - "3.7"
            - "3.11"
            - "pypy-3.9"

      name: Test
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up runner
          run: |
            mkdir actions-runner
            cd actions-runner
            Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-win-x64-2.315.0.zip -OutFile actions-runner-win-x64-2.315.0.zip
            Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.315.0.zip", "$PWD")

#        - name: Configure runner
#          run: |
#

#        - name: Start runner
#          run: .\run.cmd

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}

        - name: install dependencies
          run: |
            python -m pip install pytest .
            python -m pip install selenium

        - name: Run tests
          run: pytest -vs
