  name: Selenium_Python_CI

  on:
    push:
      branches: [ main ]
    schedule:
    - cron: '00 05 * * *'

  jobs:
    run-tests:
      timeout-minutes: 60
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          python-versions:
            - "3.11"

      name: Test_Portal_Kerja
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: ${{matrix.python-version}}

        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

        - name: Set Time Windows Server
          run: tzutil /s "SE Asia Standard Time"

        - name: Run tests
          run: | 
            cd Test
            mkdir -p reports
            python -m pytest -vs -m smoke --browser=edge --html=reports/report_action.html --self-contained-html

        - name: Set output --> upload artifact
          uses: actions/upload-artifact@v3
          if: success() || failure()
          with:
            name: test-report-hrms
            path: Test/reports/report_action.html

        - name: Send email
          uses: dawidd6/action-send-mail@v3.7.1
          with:
            server_address: smtp.gmail.com
            server_port: 465
            smtp_user: ${{ secrets.GMAIL_USERNAME }}
            smtp_password: ${{ secrets.GMAIL_PWD }}
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            body: |            
              Dear all,
              Berikut adalah hasil smoke test fitur-fitur utama portal kerja per hari ini
              
              Detail Information: 
                ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
              
              Terima kasih,
              Regards,
              Miftah Ramadhan
              QA Engineer - PT VPN
            to: ramadhanz@example.com
            from: ${{ secrets.GMAIL_USERNAME }}
            secure: true
            ignore_cert: true
            convert_markdown: true
            priority: low
            attachments: Test/reports/report_action.html



