  name: Selenium_Python_CI

  on:
    schedule:
    - cron: '50 14 * * *'
    push:
    pull_request:


  jobs:
    run-tests:
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          python-versions:
            - "3.11"

      name: Test_Portal_Kerja
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

#        - name: Set up runner
#          run: |
#            mkdir actions-runner
#            cd actions-runner
#            Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-win-x64-2.315.0.zip -OutFile actions-runner-win-x64-2.315.0.zip
#            Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.315.0.zip", "$PWD")

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: ${{matrix.python-version}}

        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

        - name: Run tests
          run: | 
            cd Test
            mkdir -p reports
            python -m pytest -vs -m smoke --browser=edge --html=reports/report_action.html --self-contained-html

        - name: Set output
          if: success() || failure()
          id: results
          run: echo "artifactPath=Test/reports/" >> $GITHUB_OUTPUT

        - uses: actions/upload-artifact@v3
          if: success() || failure()
          with:
            name: test-report-hrms
            path: Test/reports/report_action.html
