  name: DEV - HRMS Web Automation Testing

  on:
    workflow_dispatch:
      inputs:
        loglevel:
          description: 'log level'
          required: true
          default: 'warning'
        tags:
          description: 'Dev Development Tags'
    push:
      branches: [ main ]

  jobs:
    run-tests:
      timeout-minutes: 240
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          python-versions:
            - "3.11"

      name: (DEV ENV) Test HRMS Portal Kerja
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: ${{matrix.python-version}}

        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

        - name: Set Time Windows Server
          run: tzutil /s "SE Asia Standard Time"

        - name: Set secret
          shell: powershell
          run: |
            $secretValue = "${{ secrets.PASS_SUPERADM }}"
            [Environment]::SetEnvironmentVariable("PWD_SUPERADMIN", $secretValue, "Machine")
            Add-Content -Path $env:GITHUB_ENV "PWD_SUPERADMIN=$secretValue"

        - name: Run Test - Selenium with Pytest
          run: | 
            cd Test
            mkdir -p reports
            python -m pytest -vs --browser=chrome -m smoke --url=dev --html=./reports/report_in_dev.html --self-contained-html

        - name: Set output --> upload artifact
          uses: actions/upload-artifact@v4
          if: success() || failure()
          with:
            name: DEV_HRMS_Web_Automation_Test_Report
            path: Test/reports/report_in_dev.html




