  name: TEST ENV - HRMS Web Automation Testing

  on:
    workflow_dispatch:
      inputs:
        loglevel:
          description: 'log level'
          required: true
          default: 'warning'
        tags:
          description: 'Dev Development Tags'
    push:
      branches: [ main ]

  jobs:
    run-tests:
      timeout-minutes: 240
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          python-versions:
            - "3.11"

      name: Automation Test Job
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: ${{matrix.python-version}}

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

        - name: Set Time to UTC+7
          run: tzutil /s "SE Asia Standard Time"

        - name: Set Up Variable Secrets
          shell: powershell
          run: |
            $secretValue = "${{ secrets.PASS_SUPERADM }}"
            [Environment]::SetEnvironmentVariable("PWD_SUPERADMIN", $secretValue, "Machine")
            Add-Content -Path $env:GITHUB_ENV "PWD_SUPERADMIN=$secretValue"

        - name: Create Directory --> Test/reports
          run: | 
            cd Test
            mkdir -p reports

        - name: Run Pytest
          run: | 
            cd Test
            python -m pytest -vs --browser=chrome -m smoke --url=testing --html=./reports/testingEnv_hrms_automation_test_report.html --self-contained-html

        - name: Upload Report to Github Artifact
          uses: actions/upload-artifact@v4
          if: success() || failure()
          with:
            name: Staging_HRMS_AutomationTestReports
            path: Test/reports/testingEnv_hrms_automation_test_report.html